// export const ADD_TODO = "ADD_TODO";
export const ADD_TODO_LOADING = "ADD_TODO_LOADING";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_ERROR = "ADD_TODO_ERROR";

export const SET_TODO_COMPLETE = "SET_TODO_COMPLETE";
export const LOAD_TODOS_LOADING = "LOAD_TODOS_LOADING";
export const LOAD_TODOS_SUCCESS = "LOAD_TODOS_SUCCESS";
export const LOAD_TODOS_ERROR = "LOAD_TODOS_ERROR";

export const ADD_EVENT = "ADD_EVENT";
export const LOAD_EVENTS_LOADING = "LOAD_EVENTS_LOADING";
export const LOAD_EVENTS_SUCCESS = "LOAD_EVENTS_SUCCESS";
export const LOAD_EVENTS_ERROR = "LOAD_EVENTS_ERROR";